version: '3.8'
services:
  app:
      image: garmin-proj-app:latest
      env_file:
        - "V:/configs/garmin/.env"
      build: .
      container_name: garmin-project
      command: uvicorn src.main:app -host 0.0.0.0.0 -port 80 --reload
      ports: 
        - 80:80
      volumes: 
        - .:/code
        - "V:/data/garmin-uploaded-files:/data"
      depends_on:
        - redis

  redis: 
      image: redis:alpine
